# Generated by Django 4.2.4 on 2023-08-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='stuff',
        ),
    ]
